shellcheck

diff --git a/termux-url-opener b/termux-url-opener
--- a/termux-url-opener
+++ b/termux-url-opener
@@ -1,5 +1,5 @@
 #!/data/data/com.termux/files/usr/bin/bash
-cd ~/downloads
+cd ~/downloads||printf 'Proceeding, even though ~/downloads not found...\n' >&2
 function a {
 if command -v "$1"
 then
@@ -9,7 +9,7 @@ fi
 }
 a w3m 'w3m pager/browser'
 if [[ $0 =~ -file-editor$ ]]; then
-	T=file
+	T='file'
 	TN=name
 	a pager "default pager [$(realpath "$(command -v pager)")]"
 	a editor "default editor [$(realpath "$(command -v editor)")]"
